const jsondata = {
  Response: {
    ResponseStatus: 1,
    Error: {
      ErrorCode: 0,
      ErrorMessage: "",
    },
    TraceId: "742cc856-3d73-4cdd-b267-f0e4484c0984",
    Origin: "DEL",
    Destination: "BOM",
    Results: [
      [
        {
          ResultIndex: "OB1",
          Source: 24,
          IsLCC: true,
          IsRefundable: true,
          AirlineRemark: "test",
          Fare: {
            Currency: "INR",
            BaseFare: 5690,
            Tax: 2186,
            YQTax: 0,
            AdditionalTxnFeeOfrd: 0,
            AdditionalTxnFeePub: 0,
            OtherCharges: 21.74,
            ChargeBU: [
              {
                key: "TBOMARKUP",
                value: 21.74,
              },
              {
                key: "CONVENIENCECHARGE",
                value: 0,
              },
              {
                key: "OTHERCHARGE",
                value: 0,
              },
            ],
            Discount: 0,
            PublishedFare: 7917.74,
            CommissionEarned: 175.88,
            PLBEarned: 0,
            IncentiveEarned: 0,
            OfferedFare: 7721.86,
            TdsOnCommission: 35.18,
            TdsOnPLB: 0,
            TdsOnIncentive: 0,
            ServiceFee: 20,
          },
          FareBreakdown: [
            {
              Currency: "INR",
              PassengerType: 1,
              PassengerCount: 1,
              BaseFare: 2345,
              Tax: 1093,
              YQTax: 0,
              AdditionalTxnFeeOfrd: 0,
              AdditionalTxnFeePub: 0,
            },
            {
              Currency: "INR",
              PassengerType: 2,
              PassengerCount: 1,
              BaseFare: 2345,
              Tax: 1093,
              YQTax: 0,
              AdditionalTxnFee: 0,
            },
            {
              Currency: "INR",
              PassengerType: 3,
              PassengerCount: 1,
              BaseFare: 1000,
              Tax: 0,
              YQTax: 0,
              AdditionalTxnFee: 0,
            },
          ],
          Segments: [
            [
              {
                TripIndicator: 1,
                SegmentIndicator: 1,
                Airline: {
                  AirlineCode: "6E",
                  AirlineName: "Indigo",
                  FlightNumber: "171",
                  FareClass: "L",
                  OperatingCarrier: "",
                },
                Origin: {
                  Airport: {
                    AirportCode: "DEL",
                    AirportName: "Indira Gandhi Airport",
                    Terminal: "",
                    CityCode: "DEL",
                    CityName: "Delhi",
                    CountryCode: "IN",
                    CountryName: "India",
                  },
                  DepTime: "2015-11-06T05:30:00",
                },
                Destination: {
                  Airport: {
                    AirportCode: "BOM",
                    AirportName: "Mumbai",
                    Terminal: "",
                    CityCode: "BOM",
                    CityName: "Mumbai",
                    CountryCode: "IN",
                    CountryName: "India",
                  },
                  ArrTime: "2015-11-06T07:40:00",
                },
                Duration: 130,
                GroundTime: 0,
                Mile: 0,
                StopOver: false,
                StopPoint: "",
                StopPointArrivalTime: "2015-11-06T07:40:00",
                StopPointDepartureTime: "2015-11-06T05:30:00",
                Craft: "",
                IsETicketEligible: false,
                FlightStatus: "Confirmed",
                Status: "",
              },
            ],
          ],
          LastTicketDate: null,
          TicketAdvisory: null,
          FareRules: [
            {
              Origin: "DEL",
              Destination: "BOM",
              Airline: "6E",
              FareBasisCode: "L",
              FareRuleDetail: "",
              FareRestriction: "",
            },
          ],
          AirlineCode: "6E",
          ValidatingAirline: "6E",
        },
        {
          ResultIndex: "OB7",
          Source: 24,
          IsLCC: true,
          IsRefundable: true,
          AirlineRemark: "test",
          Fare: {
            Currency: "INR",
            BaseFare: 6566,
            Tax: 2248,
            YQTax: 0,
            AdditionalTxnFeeOfrd: 0,
            AdditionalTxnFeePub: 0,
            OtherCharges: 25.8,
            ChargeBU: [
              {
                key: "TBOMARKUP",
                value: 25.8,
              },
              {
                key: "CONVENIENCECHARGE",
                value: 0,
              },
              {
                key: "OTHERCHARGE",
                value: 0,
              },
            ],
            Discount: 0,
            PublishedFare: 8859.8,
            CommissionEarned: 208.72,
            PLBEarned: 0,
            IncentiveEarned: 0,
            OfferedFare: 8631.08,
            TdsOnCommission: 41.74,
            TdsOnPLB: 0,
            TdsOnIncentive: 0,
            ServiceFee: 20,
          },
          FareBreakdown: [
            {
              Currency: "INR",
              PassengerType: 1,
              PassengerCount: 1,
              BaseFare: 2783,
              Tax: 1124,
              YQTax: 0,
              AdditionalTxnFeeOfrd: 0,
              AdditionalTxnFeePub: 0,
            },
            {
              Currency: "INR",
              PassengerType: 2,
              PassengerCount: 1,
              BaseFare: 2783,
              Tax: 1124,
              YQTax: 0,
              AdditionalTxnFee: 0,
            },
            {
              Currency: "INR",
              PassengerType: 3,
              PassengerCount: 1,
              BaseFare: 1000,
              Tax: 0,
              YQTax: 0,
              AdditionalTxnFee: 0,
            },
          ],
          Segments: [
            [
              {
                TripIndicator: 1,
                SegmentIndicator: 1,
                Airline: {
                  AirlineCode: "6E",
                  AirlineName: "Indigo",
                  FlightNumber: "665",
                  FareClass: "J",
                  OperatingCarrier: "",
                },
                Origin: {
                  Airport: {
                    AirportCode: "DEL",
                    AirportName: "Indira Gandhi Airport",
                    Terminal: "",
                    CityCode: "DEL",
                    CityName: "Delhi",
                    CountryCode: "IN",
                    CountryName: "India",
                  },
                  DepTime: "2015-11-06T21:30:00",
                },
                Destination: {
                  Airport: {
                    AirportCode: "BOM",
                    AirportName: "Mumbai",
                    Terminal: "",
                    CityCode: "BOM",
                    CityName: "Mumbai",
                    CountryCode: "IN",
                    CountryName: "India",
                  },
                  ArrTime: "2015-11-06T23:35:00",
                },
                Duration: 125,
                GroundTime: 0,
                Mile: 0,
                StopOver: false,
                StopPoint: "",
                StopPointArrivalTime: "2015-11-06T23:35:00",
                StopPointDepartureTime: "2015-11-06T21:30:00",
                Craft: "",
                IsETicketEligible: false,
                FlightStatus: "Confirmed",
                Status: "",
              },
            ],
          ],
          LastTicketDate: null,
          TicketAdvisory: null,
          FareRules: [
            {
              Origin: "DEL",
              Destination: "BOM",
              Airline: "6E",
              FareBasisCode: "J",
              FareRuleDetail: "",
              FareRestriction: "",
            },
          ],
          AirlineCode: "6E",
          ValidatingAirline: "6E",
        },
      ],
    ],
  },
};
